const fs = require('fs');
var path= require('path');
const UpdateData = (data,FileName, AutoGeneratedString,FilePassword) =>{
    console.log("update -------------")
    return new Promise((resolve, reject) => {
        var exists = false
        fs.readdir(
            path.resolve(__dirname, '../UserFiles'),
            async (err, files) => {
                if (err) throw err;
                for await  (let file of files) {
                    console.log(file)
                    console.log(file.split('-'))
                    var ExistFileName = file.split('-')[0];
                    var RandomString = file.split('-')[1];
                    var ExistFilePassWord = file.split('-')[2];
                    console.log("----------")
                    if( ExistFileName === FileName && RandomString == AutoGeneratedString && ExistFilePassWord == FilePassword )
                    {
                        console.log("hye")
                        /* readFileSync Allows to read file synchronously */
                        /* while fs.readfile accepts a callback function and so works as asynchronously */
                        const content = fs.readFileSync(path.resolve(__dirname, '../UserFiles',ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'),{encoding:'utf8', flag:'r'});
                        
                        console.log("reading data ->",data)
                        if(content != ""){
                            console.log("inside->",content)
                            var filedata = JSON.parse(content);
                            console.log(filedata)
                            // filedata.push(data)
                            /* for adding values in already existing object */
                            for (const [key, value] of Object.entries(data)) {
                                filedata[key] = value
                            }
                            console.log(filedata);
                            fs.writeFileSync(path.join(__dirname,"../UserFiles",ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'), JSON.stringify(filedata));
                            // fs.writeFile(path.join(__dirname,"../UserFiles",ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'), JSON.stringify(filedata), err => {
                            //     if (err) {
                            //       console.error(err)
                            //       return 
                            //     }
                            // })
                        }
                        // fs.readFile(path.resolve(__dirname, '../UserFiles',ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'), 'utf-8', function(err, content) {
                        //     if (err) {
                        //         return;
                        //     }
                        //     else{
                                // if(content != ""){
                                //     console.log("inside->",content)
                                //     var filedata = JSON.parse(content);
                                //     console.log(filedata)
                                //     // filedata.push(data)
                                //     /* for adding values in already existing object */
                                //     for (const [key, value] of Object.entries(data)) {
                                //         filedata[key] = value
                                //     }
                                //     console.log(filedata)
                                //     fs.writeFile(path.join(__dirname,"../UserFiles",ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'), JSON.stringify(filedata), err => {
                                //         if (err) {
                                //           console.error(err)
                                //           return 
                                //         }
                                //     })
                                // }
                        //         else{
                        //             console.log("------------")
                        //             fs.appendFile(path.join(__dirname,"../UserFiles",ExistFileName+'-'+RandomString+'-'+ExistFilePassWord+'-File.json'),JSON.stringify(data), 'utf8',
                        //             // callback function
                        //             function(err) {     
                        //                 if (err) throw err;
                        //                 // if no error
                        //                 console.log("Data is appended to file successfully.")
                        //             });
                        //         }
                        //     }
                        //   });
                        exists = true
                    }
                }
                resolve(exists)
            }
        );
    })
}

module.exports.UpdateData = UpdateData